
package main.java.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OperationsService", targetNamespace = "http://model/", wsdlLocation = "http://localhost:9000/operations?wsdl")
public class OperationsService
    extends Service
{

    private final static URL OPERATIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException OPERATIONSSERVICE_EXCEPTION;
    private final static QName OPERATIONSSERVICE_QNAME = new QName("http://model/", "OperationsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/operations?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OPERATIONSSERVICE_WSDL_LOCATION = url;
        OPERATIONSSERVICE_EXCEPTION = e;
    }

    public OperationsService() {
        super(__getWsdlLocation(), OPERATIONSSERVICE_QNAME);
    }

    public OperationsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OPERATIONSSERVICE_QNAME, features);
    }

    public OperationsService(URL wsdlLocation) {
        super(wsdlLocation, OPERATIONSSERVICE_QNAME);
    }

    public OperationsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OPERATIONSSERVICE_QNAME, features);
    }

    public OperationsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OperationsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Operations
     */
    @WebEndpoint(name = "OperationsPort")
    public Operations getOperationsPort() {
        return super.getPort(new QName("http://model/", "OperationsPort"), Operations.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Operations
     */
    @WebEndpoint(name = "OperationsPort")
    public Operations getOperationsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://model/", "OperationsPort"), Operations.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OPERATIONSSERVICE_EXCEPTION!= null) {
            throw OPERATIONSSERVICE_EXCEPTION;
        }
        return OPERATIONSSERVICE_WSDL_LOCATION;
    }

}
